- name: Converge
  hosts: all
  gather_facts: false
  become: true

  vars:
    mesh_17711_stack_do__dns_stack_ops_user: "ops"
    mesh_17711_stack_do__dns_stack_quadlet_dir: "/home/ops/.config/containers/systemd"
    mesh_17711_stack_do__dns_compose_file_path: "/tmp/dns-stack.compose.yml"
    mesh_17711_stack_do__dns_unbound_image: "docker.io/crazymax/unbound:1.24.0"
    mesh_17711_stack_do__dns_adguard_image: "docker.io/adguard/adguardhome:v0.107.69"
    mesh_17711_stack_do__dns_unbound_config_dir: "/data/17711/do/dns/config"
    mesh_17711_stack_do__dns_adguard_work_dir: "/data/17711/do/adguard/work"
    mesh_17711_stack_do__dns_adguard_conf_dir: "/data/17711/do/adguard/conf"
    mesh_17711_stack_do__dns_stack_enable_unbound: true
    mesh_17711_stack_do__dns_stack_enable_adguard: true

  tasks:
    - name: Create ops user
      ansible.builtin.user:
        name: "{{ mesh_17711_stack_do__dns_stack_ops_user }}"
        state: present
        create_home: true
        shell: /bin/bash

    - name: Run ansible-role.stack-do-dns role
      ansible.builtin.import_role:
        name: "{{ playbook_dir }}/../.."
