---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - containers.podman

  tasks:
    - name: Build Podman image for Molecule
      containers.podman.podman_image:
        name: mesh-ansible-molecule
        tag: latest
        path: "{{ playbook_dir }}/../.." 
        state: build
        build:
          file: "{{ playbook_dir }}/files/Containerfile"

    - name: Create molecule instance(s)
      containers.podman.podman_container:
        name: instance
        image: mesh-ansible-molecule:latest
        state: started
        detach: true
