---
driver:
  name: podman

platforms:
  - name: instance
    image: mesh-ansible-molecule:latest
    pre_build_image: true

provisioner:
  name: ansible
  log: true
  options:
    vvv: true
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
  inventory:
    group_vars:
      all:
        ansible_user: root
        ansible_become: false
        ansible_python_interpreter: /usr/local/bin/python3
        

dependency:
  name: galaxy
  enabled: true
  options:
    force: true
    requirements-file: collections.yml

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
  #ephemeral_directory: false


