---
driver:
  name: podman

platforms:
  - name: instance
    image: localhost/mesh-ansible-molecule:latest
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: root
        ansible_become: false
        ansible_python_interpreter: /usr/local/bin/python3
        

dependency:
  name: galaxy
  enabled: false

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy

